/**
 * Node and connection data - single source of truth for the skill graph.
 * UI is rendered from this data by main.js.
 */

const COLUMNS = [
    {
        key: 'skills',
        header: 'Skill Nodes',
        nodes: [
            {
                id: 'skill_airflow',
                type: 'skill',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apacheairflow/apacheairflow-original.svg',
                alt: 'Airflow',
                title: 'Airflow',
            },
            {
                id: 'skill_athena',
                type: 'skill',
                icon: 'https://icon.icepanel.io/AWS/svg/Analytics/Athena.svg',
                alt: 'Athena',
                title: 'AWS Athena',
            },
            {
                id: 'skill_aws',
                type: 'skill',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg',
                alt: 'AWS',
                title: 'AWS Cloud',
            },
            {
                id: 'skill_ec2',
                type: 'skill',
                icon: 'https://icon.icepanel.io/AWS/svg/Compute/EC2.svg',
                alt: 'EC2',
                title: 'AWS EC2',
            },
            {
                id: 'skill_glue',
                type: 'skill',
                icon: 'https://icon.icepanel.io/AWS/svg/Analytics/Glue.svg',
                alt: 'Glue',
                title: 'AWS Glue',
            },
            {
                id: 'skill_lambda',
                type: 'skill',
                icon: 'https://icon.icepanel.io/AWS/svg/Compute/Lambda.svg',
                alt: 'Lambda',
                title: 'AWS Lambda',
            },
            {
                id: 'skill_rds',
                type: 'skill',
                icon: 'https://icon.icepanel.io/AWS/svg/Database/RDS.svg',
                alt: 'RDS',
                title: 'AWS RDS',
            },
            {
                id: 'skill_de',
                type: 'skill',
                icon: 'https://www.azureicons.com/static/images/icons/Analytics/svg/Azure-Synapse-Analytics.svg',
                alt: 'Data Eng',
                title: 'Data Engineering',
            },
            {
                id: 'skill_dw',
                type: 'skill',
                icon: './assets/images/data-warehouse-icon.png',
                alt: 'Data Warehousing',
                title: 'Data Warehousing',
            },
            {
                id: 'skill_dbt',
                type: 'skill',
                icon: './assets/images/dbt_logo.png',
                alt: 'dbt',
                title: 'dbt',
            },
            {
                id: 'skill_databricks',
                type: 'skill',
                icon: 'https://cdn.simpleicons.org/databricks/FF3621',
                alt: 'Databricks',
                title: 'Databricks',
            },
            {
                id: 'skill_etl',
                type: 'skill',
                icon: 'https://icon.icepanel.io/AWS/svg/Migration-Transfer/DataSync.svg',
                alt: 'ETL',
                title: 'ETL',
            },
            {
                id: 'skill_python',
                type: 'skill',
                icon: 'https://www.vectorlogo.zone/logos/python/python-icon.svg',
                alt: 'Python',
                title: 'Python',
            },
            {
                id: 'skill_snowflake',
                type: 'skill',
                icon: 'https://www.vectorlogo.zone/logos/snowflake/snowflake-icon.svg',
                alt: 'Snowflake',
                title: 'Snowflake',
            },
            {
                id: 'skill_sql',
                type: 'skill',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azuresqldatabase/azuresqldatabase-original.svg',
                alt: 'SQL',
                title: 'SQL',
            },
            {
                id: 'skill_terraform',
                type: 'skill',
                icon: 'https://www.vectorlogo.zone/logos/terraformio/terraformio-icon.svg',
                alt: 'Terraform',
                title: 'Terraform',
            },
        ],
    },
    {
        key: 'experience',
        header: 'Experiences',
        nodes: [
            {
                id: 'role_devsinc',
                type: 'exp',
                icon: './assets/images/devsinc_logo.jpg',
                alt: 'Devsinc',
                title: 'Devsinc',
                role: 'Associate Data Engineer',
            },
            {
                id: 'role_ml1',
                type: 'exp',
                icon: './assets/images/machine_learning_1_logo.jpeg',
                alt: 'ML1',
                title: 'Machine Learning 1 Limited',
                role: 'Associate Python Developer',
            },
            {
                id: 'role_wwa',
                type: 'exp',
                icon: './assets/images/worlwide_logo.jpeg',
                alt: 'WWA Hub',
                title: 'World Wide Admissions Hub',
                role: 'Associate Data Engineer',
            },
            {
                id: 'edu_comsats',
                type: 'edu',
                icon: './assets/images/COMSATS_logo.jpg',
                alt: 'COMSATS',
                title: 'COMSATS Institute of Information and Technology',
                role: 'BS Computer Science',
            },
        ],
    },
    {
        key: 'certifications',
        header: 'Certifications',
        nodes: [
            {
                id: 'cert_dbt',
                type: 'cert',
                icon: './assets/images/dbt_logo.png',
                alt: 'dbt',
                title: 'dbt Fundamentals',
                badge: 'dbt Labs',
            },
            {
                id: 'cert_snow',
                type: 'cert',
                icon: 'https://www.vectorlogo.zone/logos/snowflake/snowflake-icon.svg',
                alt: 'Snowflake',
                title: 'Snowflake Data Engineering',
                badge: 'Snowflake',
            },
            {
                id: 'cert_aws_de',
                type: 'cert',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg',
                alt: 'AWS',
                title: 'Data Engineering on AWS - Foundations',
                badge: 'AWS',
            },
            {
                id: 'cert_databricks_de',
                type: 'cert',
                icon: 'https://cdn.simpleicons.org/databricks/FF3621',
                alt: 'Databricks',
                title: 'Databricks for Data Engineering',
                badge: 'Databricks',
            },
            {
                id: 'cert_datacamp',
                type: 'cert',
                icon: 'https://cdn.simpleicons.org/datacamp/03EF62',
                alt: 'DataCamp',
                title: 'Data Engineer',
                badge: 'DataCamp',
            },
            {
                id: 'cert_python',
                type: 'cert',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg',
                alt: 'Google',
                title: 'Crash Course on Python',
                badge: 'Google',
            },
            {
                id: 'cert_sql',
                type: 'cert',
                icon: 'https://www.vectorlogo.zone/logos/ibm/ibm-icon.svg',
                alt: 'IBM',
                title: 'Querying Databases with SQL',
                badge: 'IBM',
            },
            {
                id: 'cert_intro_de',
                type: 'cert',
                icon: 'https://www.deeplearning.ai/favicon.ico',
                alt: 'DeepLearning.AI',
                title: 'Introduction to Data Engineering',
                badge: 'DeepLearning.AI',
            },
            {
                id: 'cert_python_getstarted',
                type: 'cert',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg',
                alt: 'Google',
                title: 'Get Started with Python',
                badge: 'Google',
            },
            {
                id: 'cert_programming_python',
                type: 'cert',
                icon: 'https://cdn.simpleicons.org/meta/0668E1',
                alt: 'Meta',
                title: 'Programming in Python',
                badge: 'Meta',
            },
            {
                id: 'cert_python_ds_ai',
                type: 'cert',
                icon: 'https://www.vectorlogo.zone/logos/ibm/ibm-icon.svg',
                alt: 'IBM',
                title: 'Python for Data Science and AI',
                badge: 'IBM',
            },
        ],
    },
    {
        key: 'projects',
        header: 'Deployed Projects',
        nodes: [
            {
                id: 'proj_youtube',
                type: 'proj',
                icon: 'https://cdn.jsdelivr.net/npm/heroicons@2.2.0/24/solid/code-bracket.svg',
                alt: 'Project',
                title: "YouTube's Data Engineering: ETL & Cloud Pipeline Project",
                badge: 'Portfolio',
            },
            {
                id: 'proj_terraform',
                type: 'proj',
                icon: 'https://cdn.jsdelivr.net/npm/heroicons@2.2.0/24/solid/code-bracket.svg',
                alt: 'Project',
                title: 'Terraform-Powered AWS Glue ETL: Infrastructure as Code for Data Pipelines',
                badge: 'Portfolio',
            },
            {
                id: 'proj_airflow',
                type: 'proj',
                icon: 'https://cdn.jsdelivr.net/npm/heroicons@2.2.0/24/solid/code-bracket.svg',
                alt: 'Project',
                title: 'Simple Cloud-Based Data Pipeline with Apache Airflow on AWS EC2',
                badge: 'Portfolio',
            },
            {
                id: 'proj_snow_medallion',
                type: 'proj',
                icon: 'https://cdn.jsdelivr.net/npm/heroicons@2.2.0/24/solid/code-bracket.svg',
                alt: 'Project',
                title: 'Snowflake SQL Medallion Warehouse',
                badge: 'Portfolio',
            },
            {
                id: 'proj_dbt_snowflake',
                type: 'proj',
                icon: 'https://cdn.jsdelivr.net/npm/heroicons@2.2.0/24/solid/code-bracket.svg',
                alt: 'Project',
                title: 'Modern Data Modeling with dbt on Snowflake',
                badge: 'Portfolio',
            },
        ],
    },
];

const CONNECTIONS = [
    ['skill_dbt', 'role_devsinc'],
    ['skill_dbt', 'cert_dbt'],
    ['skill_dbt', 'proj_dbt_snowflake'],
    ['skill_snowflake', 'role_devsinc'],
    ['skill_snowflake', 'cert_snow'],
    ['skill_snowflake', 'proj_dbt_snowflake'],
    ['skill_snowflake', 'proj_snow_medallion'],
    ['skill_de', 'role_devsinc'],
    ['skill_de', 'role_wwa'],
    ['skill_de', 'edu_comsats'],
    ['skill_de', 'cert_aws_de'],
    ['skill_databricks', 'cert_databricks_de'],
    ['skill_de', 'cert_databricks_de'],
    ['skill_de', 'cert_datacamp'],
    ['skill_de', 'cert_intro_de'],
    ['skill_de', 'cert_snow'],
    ['skill_de', 'proj_youtube'],
    ['skill_de', 'proj_airflow'],
    ['skill_de', 'proj_terraform'],
    ['skill_de', 'proj_dbt_snowflake'],
    ['skill_de', 'proj_snow_medallion'],
    ['skill_python', 'role_ml1'],
    ['skill_python', 'role_wwa'],
    ['skill_python', 'edu_comsats'],
    ['skill_python', 'cert_python'],
    ['skill_python', 'cert_datacamp'],
    ['skill_python', 'cert_python_getstarted'],
    ['skill_python', 'cert_programming_python'],
    ['skill_python', 'cert_python_ds_ai'],
    ['skill_python', 'proj_youtube'],
    ['skill_python', 'proj_terraform'],
    ['skill_python', 'proj_airflow'],
    ['skill_sql', 'edu_comsats'],
    ['skill_sql', 'cert_sql'],
    ['skill_sql', 'cert_datacamp'],
    ['skill_sql', 'role_devsinc'],
    ['skill_sql', 'proj_terraform'],
    ['skill_sql', 'proj_snow_medallion'],
    ['skill_sql', 'proj_dbt_snowflake'],
    ['skill_etl', 'role_wwa'],
    ['skill_etl', 'edu_comsats'],
    ['skill_etl', 'proj_youtube'],
    ['skill_etl', 'proj_terraform'],
    ['skill_etl', 'proj_airflow'],
    ['skill_etl', 'cert_intro_de'],
    ['skill_dw', 'edu_comsats'],
    ['skill_dw', 'role_devsinc'],
    ['skill_dw', 'proj_snow_medallion'],
    ['skill_aws', 'cert_intro_de'],
    ['skill_aws', 'cert_aws_de'],
    ['skill_aws', 'role_devsinc'],
    ['skill_aws', 'proj_youtube'],
    ['skill_aws', 'proj_terraform'],
    ['skill_aws', 'proj_airflow'],
    ['skill_airflow', 'role_devsinc'],
    ['skill_airflow', 'proj_airflow'],
    ['skill_lambda', 'proj_youtube'],
    ['skill_glue', 'proj_youtube'],
    ['skill_glue', 'proj_terraform'],
    ['skill_athena', 'proj_youtube'],
    ['skill_athena', 'proj_terraform'],
    ['skill_terraform', 'proj_terraform'],
    ['skill_rds', 'proj_terraform'],
    ['skill_ec2', 'proj_airflow'],
];
